#!/bin/sh

. /etc/rc.subr

name=transmission_vpn_monitor
rcvar=transmission_vpn_monitor_enable

command="/usr/sbin/${name}

load_rc_config $name

: ${transmission_vpn_monitor_enable="NO"

run_rc_command "$1"
